### ISSUE TITLE
Beautify?

### ISSUE THREAD

**Issue by Derjyn** [ue4plugins/TextAsset#2]
This does what it says on the tin, but some love to the UI style could kick it up a notch:

- Some padding on the editor space itself for "comfort"
- Monospace font (or even being able to select a font from assets)
- Sizing...
- Tab support (tabulation, rather, while we're at it, support for converting tabs to spaces for bonus points)

**Comment by gmpreussner** [comment]
Those are all great suggestions. Wanna send me a pull request? I have very little time right now. Thanks!

**Comment by gmpreussner** [comment]
I added Editor Preferences for TextAsset that allows for customizing the text appearance. The tab character is currently not supported by SMultilineEditableTextBox (tab key is used for widget focus switching). I'll talk to the Tools team to see if they can change it.
